# Header
menu:
    首页: /
    案例: /stories
    新闻: /archives
    关于: /about

# Content
excerpt_link: 阅读全文

# Toc
toc: false

# MIIT ICP/IP/DOMAIN
beian:
    enable: false
    number:
    url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /favicon.ico
webclip: /images/webclip
brand: /images/logo.png

# Jumbotron video & Hero image
## Jumbotron video
video:
    overlay: true
    path: /images/
## Hero image
hero:
    image: /images/banner.jpg
## keen-slider
keen_slider:
    enable: false

# Slogan
slogan:
    primary: 钛度科技
    secondary: 态度决定行为，行为培养性格，性格决定命运
    archives: 汇聚热点话题 打造创新思路
    pages: 运维更智能 部署更方便 应用更便捷
    posts: 实践见真知既是最好的解释
